### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by LNJ2** [Rui914/Japanese_Modpack#1]
I didn't found any license? Which is it?
I would like to use the sakura tree texture for my game Minetest TNG! :)

**Comment by Rui914** [comment]
Sakura tree texture is licensed under WTFPL.
It was made by me.

**Comment by Rui914** [comment]
However, other codes/textures isn't licensed. Please don't use them.

**Comment by Rui914** [comment]
Also I'll delete this repo and I'm going to rework that to new repo.

New repo:
https://github.com/Rui914/japan_modpack

**Comment by LNJ2** [comment]
Ok! Thanks! :)
